apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: docker.io/pro696969/urlshort:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "5m"
            memory: "70Mi"
          limits:
            cpu: "100m"
            memory: "150Mi"
        env:
        - name: REDIS_SENTINELS
          valueFrom:
            configMapKeyRef:
              name: flask-app-configmap
              key: REDIS_SENTINELS
        - name: REDIS_MASTER
          valueFrom:
            configMapKeyRef:
              name: flask-app-configmap
              key: REDIS_MASTER
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flask-app-secret
              key: REDIS_PASSWORD

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flask-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-app
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30007
