apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-app-configmap
data:
  # property-like keys; each key maps to a simple value
  REDIS_SENTINELS: "sentinel-0.sentinel.redis.svc.cluster.local:5000,sentinel-1.sentinel.redis.svc.cluster.local:5000,sentinel-2.sentinel.redis.svc.cluster.local:5000"
  REDIS_MASTER: "mymaster"